"""Create New Test

Revision ID: 079c95633a96
Revises: e1c7e7730f80
Create Date: 2025-05-20 16:38:32.102547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079c95633a96'
down_revision: Union[str, None] = 'e1c7e7730f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
