"""Create New Test

Revision ID: fb67c6d0ea70
Revises: 079c95633a96
Create Date: 2025-05-20 16:51:42.717917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb67c6d0ea70'
down_revision: Union[str, None] = '079c95633a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'country')
    # ### end Alembic commands ###
